# Generated by Django 4.2.1 on 2023-05-20 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spam',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='saved_contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter Valid Phone Number', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='spam',
            name='reported_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter Valid Phone Number', regex='^\\+?1?\\d{10}$')]),
        ),
    ]
