# Generated by Django 4.2.1 on 2023-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_id_spam_id_alter_contact_saved_contact_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(models.F('user'), models.F('saved_contact'), name='user_contact_pair'),
        ),
        migrations.AddConstraint(
            model_name='spam',
            constraint=models.UniqueConstraint(models.F('user'), models.F('reported_number'), name='user_reported_number'),
        ),
    ]
